In [1]:
import pandas as pd
path='C://users/naikp/Database/GlobalTemperatures.csv'
data=pd.read_csv(path)
data

,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
0,1750-01-01,3.034,3.574,NaN,NaN,NaN,NaN,NaN,NaN
1,1750-02-01,3.083,3.702,NaN,NaN,NaN,NaN,NaN,NaN
2,1750-03-01,5.626,3.076,NaN,NaN,NaN,NaN,NaN,NaN
3,1750-04-01,8.490,2.451,NaN,NaN,NaN,NaN,NaN,NaN
4,1750-05-01,11.573,2.072,NaN,NaN,NaN,NaN,NaN,NaN
5,1750-06-01,12.937,1.724,NaN,NaN,NaN,NaN,NaN,NaN
6,1750-07-01,15.868,1.911,NaN,NaN,NaN,NaN,NaN,NaN
7,1750-08-01,14.750,2.231,NaN,NaN,NaN,NaN,NaN,NaN
8,1750-09-01,11.413,2.637,NaN,NaN,NaN,NaN,NaN,NaN
9,1750-10-01,6.367,2.668,NaN,NaN,NaN,NaN,NaN,NaN
10,1750-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1750-12-01,2.772,2.970,NaN,NaN,NaN,NaN,NaN,NaN
12,1751-01-01,2.495,3.469,NaN,NaN,NaN,NaN,NaN,NaN
13,1751-02-01,0.963,3.827,NaN,NaN,NaN,NaN,NaN,NaN
14,1751-03-01,5.800,3.051,NaN,NaN,NaN,NaN,NaN,NaN
15,1751-04-01,7.670,2.368,NaN,NaN,NaN,NaN,NaN,NaN
16,1751-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1751-06-01,13.827,1.801,NaN,NaN,NaN,NaN,NaN,NaN
18,1751-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1751-08-01,14.405,2.296,NaN,NaN,NaN,NaN,NaN,NaN
20,1751-09-01,10.673,2.656,NaN,NaN,NaN,NaN,NaN,NaN
21,1751-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1751-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1751-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1752-01-01,0.348,3.789,NaN,NaN,NaN,NaN,NaN,NaN
25,1752-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1752-03-01,5.806,3.192,NaN,NaN,NaN,NaN,NaN,NaN
27,1752-04-01,8.265,2.398,NaN,NaN,NaN,NaN,NaN,NaN
28,1752-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1752-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3162,2013-07-01,15.003,0.126,20.737,0.100,9.330,0.153,17.503,0.068
3163,2013-08-01,14.742,0.129,20.596,0.120,9.014,0.179,17.462,0.068
3164,2013-09-01,13.154,0.104,18.947,0.077,7.482,0.194,16.894,0.064
3165,2013-10-01,10.256,0.077,15.994,0.100,4.663,0.135,15.905,0.062
3166,2013-11-01,7.424,0.079,12.965,0.113,2.016,0.116,15.107,0.062
3167,2013-12-01,4.724,0.085,10.083,0.129,-0.548,0.105,14.339,0.065
3168,2014-01-01,3.732,0.075,9.327,0.138,-1.755,0.091,14.136,0.064
3169,2014-02-01,3.500,0.068,9.146,0.073,-2.080,0.095,14.157,0.065
3170,2014-03-01,6.378,0.098,12.367,0.108,0.436,0.139,15.090,0.068
3171,2014-04-01,9.589,0.111,15.529,0.090,3.617,0.193,16.038,0.069
3172,2014-05-01,12.582,0.068,18.362,0.158,6.613,0.166,16.804,0.059
3173,2014-06-01,14.335,0.096,20.126,0.095,8.473,0.157,17.303,0.064
3174,2014-07-01,14.873,0.078,20.711,0.091,9.112,0.135,17.508,0.061
3175,2014-08-01,14.875,0.115,20.790,0.098,9.047,0.173,17.607,0.064
3176,2014-09-01,13.091,0.086,18.865,0.106,7.399,0.155,16.975,0.059
3177,2014-10-01,10.330,0.076,16.066,0.111,4.689,0.126,16.029,0.059
3178,2014-11-01,6.713,0.121,12.284,0.124,1.313,0.115,14.899,0.064
3179,2014-12-01,4.850,0.090,10.190,0.148,-0.331,0.123,14.410,0.062
3180,2015-01-01,3.881,0.130,9.432,0.090,-1.518,0.097,14.255,0.066
3181,2015-02-01,4.664,0.121,10.497,0.092,-1.138,0.113,14.564,0.067
3182,2015-03-01,6.740,0.060,12.659,0.096,0.894,0.079,15.193,0.061
3183,2015-04-01,9.313,0.088,15.224,0.137,3.402,0.147,15.962,0.061
3184,2015-05-01,12.312,0.081,18.181,0.117,6.313,0.153,16.774,0.058
3185,2015-06-01,14.505,0.068,20.364,0.133,8.627,0.168,17.390,0.057
3186,2015-07-01,15.051,0.086,20.904,0.109,9.326,0.225,17.611,0.058
3187,2015-08-01,14.755,0.072,20.699,0.110,9.005,0.170,17.589,0.057
3188,2015-09-01,12.999,0.079,18.845,0.088,7.199,0.229,17.049,0.058
3189,2015-10-01,10.801,0.102,16.450,0.059,5.232,0.115,16.290,0.062
3190,2015-11-01,7.433,0.119,12.892,0.093,2.157,0.106,15.252,0.063
3191,2015-12-01,5.518,0.100,10.725,0.154,0.287,0.099,14.774,0.062

In [4]:
data.describe()

,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
count,3180.000000,3180.000000,1992.000000,1992.000000,1992.000000,1992.000000,1992.000000,1992.000000
mean,8.374731,0.938468,14.350601,0.479782,2.743595,0.431849,15.212566,0.128532
std,4.381310,1.096440,4.309579,0.583203,4.155835,0.445838,1.274093,0.073587
min,-2.080000,0.034000,5.900000,0.044000,-5.407000,0.045000,12.475000,0.042000
25%,4.312000,0.186750,10.212000,0.142000,-1.334500,0.155000,14.047000,0.063000
50%,8.610500,0.392000,14.760000,0.252000,2.949500,0.279000,15.251000,0.122000
75%,12.548250,1.419250,18.451500,0.539000,6.778750,0.458250,16.396250,0.151000
max,19.021000,7.880000,21.320000,4.373000,9.715000,3.498000,17.611000,0.457000

In [5]:
import statistics

In [6]:
data['LandAverageTemperature'].describe()

count    3180.000000
mean        8.374731
std         4.381310
min        -2.080000
25%         4.312000
50%         8.610500
75%        12.548250
max        19.021000
Name: LandAverageTemperature, dtype: float64

In [23]:
data['LandAverageTemperature'].describe(percentiles=[.10,.30,.65,.80])

count    3180.000000
mean        8.374731
std         4.381310
min        -2.080000
10%         2.563900
30%         4.956700
50%         8.610500
65%        11.228700
80%        13.228400
max        19.021000
Name: LandAverageTemperature, dtype: float64

In [7]:
data['LandAverageTemperature'].mean()#avg value

8.374731132075466

In [8]:
data['LandAverageTemperature'].cumsum() #cumulative sum

0           3.034
1           6.117
2          11.743
3          20.233
4          31.806
5          44.743
6          60.611
7          75.361
8          86.774
9          93.141
10            NaN
11         95.913
12         98.408
13         99.371
14        105.171
15        112.841
16            NaN
17        126.668
18            NaN
19        141.073
20        151.746
21            NaN
22            NaN
23            NaN
24        152.094
25            NaN
26        157.900
27        166.165
28            NaN
29            NaN
          ...
3162    26348.525
3163    26363.267
3164    26376.421
3165    26386.677
3166    26394.101
3167    26398.825
3168    26402.557
3169    26406.057
3170    26412.435
3171    26422.024
3172    26434.606
3173    26448.941
3174    26463.814
3175    26478.689
3176    26491.780
3177    26502.110
3178    26508.823
3179    26513.673
3180    26517.554
3181    26522.218
3182    26528.958
3183    26538.271
3184    26550.583
3185    26565.088
3186    26580.139
3187    26594.894
3188    26607.893
3189    26618.694
3190    26626.127
3191    26631.645
Name: LandAverageTemperature, Length: 3192, dtype: float64

In [9]:
data['LandAverageTemperature'].max()

19.021

In [10]:
data['LandAverageTemperature'].min()

-2.08

In [11]:
data['LandAverageTemperature'].sum()

26631.644999999997

In [25]:
data['LandAverageTemperature'].sum(skipna=True)

26631.644999999997

In [26]:
data['LandAverageTemperature'].sum(skipna=False)

nan

In [13]:
data['LandAverageTemperature'].median()#middle value

8.610499999999998

In [14]:
data['LandAverageTemperature'].std()

4.381309770725171

In [15]:
data['LandAverageTemperature'].count() #no. of non-na values

3180

In [17]:
data.shape

(3192, 9)

In [19]:
data['LandAverageTemperature'].var()#variance

19.19587530705185

In [2]:
#Covariance Matrix Of Values
data.cov()

,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
LandAverageTemperature,19.195875,-0.980903,18.295532,-0.269670,17.639358,-0.318273,5.366879,-0.041226
LandAverageTemperatureUncertainty,-0.980903,1.202180,-0.128316,0.113270,-0.153681,0.088766,-0.059373,0.016031
LandMaxTemperature,18.295532,-0.128316,18.572471,-0.264779,17.791761,-0.307458,5.402156,-0.038234
LandMaxTemperatureUncertainty,-0.269670,0.113270,-0.264779,0.340126,-0.298722,0.225875,-0.121412,0.036926
LandMinTemperature,17.639358,-0.153681,17.791761,-0.298722,17.270967,-0.343721,5.222922,-0.047380
LandMinTemperatureUncertainty,-0.318273,0.088766,-0.307458,0.225875,-0.343721,0.198771,-0.125960,0.028873
LandAndOceanAverageTemperature,5.366879,-0.059373,5.402156,-0.121412,5.222922,-0.125960,1.623313,-0.019039
LandAndOceanAverageTemperatureUncertainty,-0.041226,0.016031,-0.038234,0.036926,-0.047380,0.028873,-0.019039,0.005415

In [3]:
#Correlation Matrix Of Values
data.corr()

,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
LandAverageTemperature,1.000000,-0.204191,0.995807,-0.108462,0.995611,-0.167451,0.988066,-0.131412
LandAverageTemperatureUncertainty,-0.204191,1.000000,-0.132905,0.866944,-0.165066,0.888717,-0.208008,0.972405
LandMaxTemperature,0.995807,-0.132905,1.000000,-0.105349,0.993404,-0.160020,0.983855,-0.120563
LandMaxTemperatureUncertainty,-0.108462,0.866944,-0.105349,1.000000,-0.123251,0.868702,-0.163396,0.860425
LandMinTemperature,0.995611,-0.165066,0.993404,-0.123251,1.000000,-0.185512,0.986402,-0.154931
LandMinTemperatureUncertainty,-0.167451,0.888717,-0.160020,0.868702,-0.185512,1.000000,-0.221746,0.880062
LandAndOceanAverageTemperature,0.988066,-0.208008,0.983855,-0.163396,0.986402,-0.221746,1.000000,-0.203072
LandAndOceanAverageTemperatureUncertainty,-0.131412,0.972405,-0.120563,0.860425,-0.154931,0.880062,-0.203072,1.000000

In [5]:
#Kurtosis of preTestScore values
data['LandAverageTemperature'].kurt()

-1.3420724591854307

In [6]:
#Skewness of preTestScore values
data['LandAverageTemperature'].skew()

-0.08142566547693746